### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by dulmandakh** [reactjs/mn.reactjs.org#11]
Hey @tesseralis,

Is it possible to setup CI so that we generate a site for each PR, and also for master branch, where contributors can go and see their changes, but also current state. We would like to invite not tech savvy people to review translations from language standpoint, and it's not feasible to ask install toolchains, then build.

Thank you

**Comment by tesseralis** [comment]
Hi @dulmandakh,

You should be able to set up CI by choosing one of the services listed [here](https://github.com/reactjs/reactjs.org-translation/blob/master/maintainer-guide.md#integration-tools) and following the instructions.

Please let me know if you need further help.
