### ISSUE TITLE
Community доторх Support page орчуулга

### ISSUE THREAD

**Issue by jagaa1103** [reactjs/mn.reactjs.org#5]
Support.md-ийг орчуулж үзлээ. Санал сэтгэгдлээ хэлээрэй.

**Comment by Zorig** [comment]
Pull Request үүсгээрэй

**Comment by jagaa1103** [comment]
@Zorig үүсгэсэн, болж байна уу?

**Comment by Zorig** [comment]
@jagaa1103 болсон merge хийгдсэн

**Comment by jagaa1103** [comment]
@Zorig боломжтой бол оролцож байхыг хичээнээ. Амжилт

**Comment by Zorig** [comment]
👍

**Comment by dulmandakh** [comment]
@jagaa1103 идэвхитэй оролцож байгаарай, хүн бүрийн оролцоо маш чухал шүү 👍
