### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by batbayar-su** [reactjs/mn.reactjs.org#50]
`content/docs/getting-started.md`

**Comment by Zorig** [comment]
@batbayar-su ?

**Comment by batbayar-su** [comment]
Sorry, ajiltai baigaad amjsangui oiriin odroos oruulnaa 🙏

**Comment by batbayar-su** [comment]
- [x]  Intro
- [x] Try React
- [ ] Learn React (WIP)
- [ ] Stay Informed
- [ ] Versioned documentation
- [ ] Missing something?

**Comment by batbayar-su** [comment]
@Zorig review hiigeed ogoorei 🙏 #71
